### ISSUE TITLE
Replace print calls with logging module

### ISSUE THREAD

**Issue by tomschr** [dvdme/forecastiopy#10]
Thanks for this library and your efforts! 👍

Looking into your source code, I would kindly suggest to replace all print calls with [Python's logging module](https://docs.python.org/3/library/logging.html#module-logging) for the following reasons:

* Easier to configure
* Easier to test
* Python's logging module allows to have different receivers for logging output (by stdout, mail, etc.)
* Separates error messages from debug or information messages
* Separates normal output for the user with logging output. Each serves different purposes.

Your code uses `print` a lot. For example, in file [ForecastIO.py](https://github.com/dvdme/forecastiopy/blob/master/forecastiopy/ForecastIO.py#L147), there are a couple of `print`s. IMHO, I see the following problems with this approach:

* Error messages should always go to stderr, never to stdout. If they go to stdout, they mix with "normal" messages for the user. It's hard or impossible to redirect error message into a file, for example.
* If you really have to use `print`, redirect your output to stderr like this: `print("error:", err, file=sys.stderr)` 

So better use `logging.error` instead of print as stated above. 😄

**Comment by dvdme** [comment]
That makes total sense and I will use your suggestion next time I make new developments.

**Comment by PvtHaggard** [comment]
I have put in a pull request with the logging module implemented. #11

**Comment by dvdme** [comment]
Pull request merge and updated package in PyPi
