### ISSUE TITLE
Invalid API keys should be an exception

### ISSUE THREAD

**Issue by kousu** [dvdme/forecastiopy#3]
```
>>> fio = ForecastIO.ForecastIO("fds", latitude=83.6906, longitude=-39.4176)
The API Key doesn't seam to be valid.
>>> fio
<forecastiopy.ForecastIO.ForecastIO object at 0x7f573b300940>
>>> FIODaily.FIODaily(fio)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kousu/.local/lib/python3.4/site-packages/forecastiopy-0.1-py3.4.egg/forecastiopy/FIODaily.py", line 20, in __init__
    if forecast_io.has_daily():
  File "/home/kousu/.local/lib/python3.4/site-packages/forecastiopy-0.1-py3.4.egg/forecastiopy/ForecastIO.py", line 204, in has_daily
    return 'daily' in self.forecast
AttributeError: 'ForecastIO' object has no attribute 'forecast'
```

The real mistake here is that the API key is wrong, but the exception that actually crashes is obscure and makes it seem like maybe there's a library version mismatch or something else frustratingly impossible to fix. I wrote a largish script, ported it to a new host, and accidentally misimported my API key, so I didn't notice the first message and was focusing on the second exception.

Would you make that initial line into an exception instead of just a print?

**Comment by dvdme** [comment]
That makes total sense and yes, it is a better design. 
I already made the change and pushed it to the `fix_wrong_ids` branch.
Can you check it?

**Comment by dvdme** [comment]
Merged to master and published to pip
